# Generated by Django 6.0.6 on 2026-07-05 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_application_has_ssl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('responsable', models.CharField(blank=True, max_length=255, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('numero_contrat', models.CharField(max_length=120, unique=True, verbose_name='Numéro de contrat')),
                ('contract_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('SUPPORT', 'Support'), ('GARANTIE', 'Garantie'), ('RENOUVELLEMENT', 'Renouvellement')], max_length=20, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('cout_annuel', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Coût annuel')),
                ('sla', models.CharField(max_length=255, verbose_name='SLA')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_ATTENTE', 'En attente'), ('EXPIRE', 'Expiré')], default='ACTIF', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='applications.application', verbose_name='Application')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='contrats.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut', 'numero_contrat'],
            },
        ),
    ]
