# Generated by Django 6.0.6 on 2026-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contrats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archivé"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archivé"),
        ),
    ]
