"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xf5h%%pn2##@&5n2ufl3@lmr(x8hn5zxzn-o6&1ev5&u151*z)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'applications',
    'environments',
    'domaines',
    'certificats_ssl',
    'documentation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'certificats_ssl.context_processors.ssl_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Local Docker dev uses SQLite when USE_SQLITE is set to 1/true/yes.
# Production uses Supabase PostgreSQL when USE_SQLITE is 0/false/no.

USE_SQLITE = os.environ.get('USE_SQLITE', '').strip().lower() in ('1', 'true', 'yes')

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres.jddyycaouofnlgbeofba'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'eraDmP1OVQEYcDxQ'),
            'HOST': os.environ.get('DB_HOST', 'aws-1-eu-central-1.pooler.supabase.com'),
            'PORT': os.environ.get('DB_PORT', '6543'),
            'OPTIONS': {
                'sslmode': 'require',
            },
            'DISABLE_SERVER_SIDE_CURSORS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPABASE_STORAGE_ENABLED = os.environ.get('SUPABASE_STORAGE_ENABLED', '').strip().lower() in ('1', 'true', 'yes')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', '')
SUPABASE_STORAGE_ACCESS_KEY = os.environ.get('SUPABASE_STORAGE_ACCESS_KEY', '')
SUPABASE_STORAGE_SECRET_KEY = os.environ.get('SUPABASE_STORAGE_SECRET_KEY', '')
SUPABASE_STORAGE_ENDPOINT = os.environ.get('SUPABASE_STORAGE_ENDPOINT', '')
SUPABASE_STORAGE_REGION = os.environ.get('SUPABASE_STORAGE_REGION', 'eu-central-1')

AWS_ACCESS_KEY_ID = SUPABASE_STORAGE_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = SUPABASE_STORAGE_SECRET_KEY
AWS_STORAGE_BUCKET_NAME = SUPABASE_STORAGE_BUCKET
AWS_S3_ENDPOINT_URL = SUPABASE_STORAGE_ENDPOINT
AWS_S3_REGION_NAME = SUPABASE_STORAGE_REGION
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_VERSION = 's3v4'

if SUPABASE_STORAGE_ENABLED and not USE_SQLITE:
    STORAGES = {
        'default': {
            'BACKEND': 'config.storage_backends.SupabaseMediaStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'

# ─── Authentication Backends ────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'accounts.backends.MatriculeOrEmailBackend',  # Login via matricule or email
    'django.contrib.auth.backends.ModelBackend',  # Fallback (Django admin)
]

# ─── Email / SMTP Configuration ────────────────────────────────────────────────
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = 'nessimzitouni11@gmail.com'
EMAIL_HOST_PASSWORD = 'dzzf oczr bwvu mhtr'
DEFAULT_FROM_EMAIL  = 'APM Project <nessimzitouni11@gmail.com>'

# ─── Alertes SSL ───────────────────────────────────────────────────────────────
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
SSL_ALERT_RAPPEL_JOURS = int(os.environ.get('SSL_ALERT_RAPPEL_JOURS', '7'))

SMS_ENABLED = os.environ.get('SMS_ENABLED', '').strip().lower() in ('1', 'true', 'yes')
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_FROM_NUMBER', '')

