# Generated by Django 6.0.6 on 2026-06-28 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('criticite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('CRITIQUE', 'Critique')], max_length=10, verbose_name='Criticité')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('date_mise_en_production', models.DateField(verbose_name='Date de mise en production')),
                ('date_fin_vie', models.DateField(blank=True, null=True, verbose_name='Date de fin de vie')),
                ('direction_metier', models.CharField(max_length=255, verbose_name='Direction métier')),
                ('nombre_utilisateurs', models.PositiveIntegerField(verbose_name="Nombre d'utilisateurs")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_de_projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_chef_projet', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet')),
                ('equipe_support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_support', to=settings.AUTH_USER_MODEL, verbose_name='Équipe support')),
                ('responsable_metier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_metier', to=settings.AUTH_USER_MODEL, verbose_name='Responsable métier')),
                ('responsable_technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_technique', to=settings.AUTH_USER_MODEL, verbose_name='Responsable technique')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['nom'],
            },
        ),
    ]
