# Generated by Django 6.0.6 on 2026-07-10 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_has_ssl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='chef_de_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_chef_projet', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='equipe_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_support', to=settings.AUTH_USER_MODEL, verbose_name='Équipe support'),
        ),
        migrations.AlterField(
            model_name='application',
            name='responsable_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_technique', to=settings.AUTH_USER_MODEL, verbose_name='Responsable technique'),
        ),
    ]
