# Generated by Django 6.0.6 on 2026-07-11 13:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_count', models.IntegerField(default=1)),
                ('total_ram', models.FloatField(default=0.0)),
                ('total_disk', models.FloatField(default=0.0)),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VMMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.virtualmachine')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
