# Generated by Django 6.0.6 on 2026-07-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl', '0002_alertes_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatssl',
            options={'ordering': ['date_expiration'], 'verbose_name': 'Certificat SSL', 'verbose_name_plural': 'Certificats SSL'},
        ),
        migrations.AlterField(
            model_name='certificatssl',
            name='emetteur',
            field=models.CharField(max_length=255, verbose_name='Fournisseur SSL'),
        ),
        migrations.AlterField(
            model_name='certificatssl',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('A_RENOUVELER', 'À renouveler')], default='ACTIF', max_length=15, verbose_name='État du certificat'),
        ),
    ]
