# Generated by Django 6.0.6 on 2026-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de domaine')),
                ('registrar', models.CharField(max_length=255, verbose_name='Registrar')),
                ('dns', models.CharField(max_length=255, verbose_name='DNS')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('date_achat', models.DateField(verbose_name='Date d’achat')),
                ('date_expiration', models.DateField(verbose_name='Date d’expiration')),
                ('renouvellement_auto', models.BooleanField(default=False, verbose_name='Renouvellement automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['nom'],
            },
        ),
    ]
