# Generated by Django 6.0.6 on 2026-06-29 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='Nom du serveur')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, protocol='both', unpack_ipv4=True, verbose_name='Adresse IP')),
                ('systeme_exploitation', models.CharField(blank=True, max_length=100, verbose_name='Système')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Serveur',
                'verbose_name_plural': 'Serveurs',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Environnement',
            fields=[
                ('id_environnement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('os', models.CharField(max_length=100, verbose_name='OS')),
                ('cpu', models.CharField(max_length=100, verbose_name='CPU')),
                ('ram', models.CharField(max_length=100, verbose_name='RAM')),
                ('hebergeur', models.CharField(max_length=255, verbose_name='Hébergeur')),
                ('type_hebergement', models.CharField(choices=[('ON_PREMISE', 'On-premise'), ('CLOUD', 'Cloud'), ('HYBRIDE', 'Hybride'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type d’hébergement')),
                ('docker', models.BooleanField(default=False, verbose_name='Docker')),
                ('kubernetes', models.BooleanField(default=False, verbose_name='Kubernetes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environnements', to='applications.application', verbose_name='Application')),
                ('serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environnements', to='environments.server', verbose_name='Serveur')),
            ],
            options={
                'verbose_name': 'Environnement',
                'verbose_name_plural': 'Environnements',
                'ordering': ['nom'],
            },
        ),
    ]
